version: '3.8'

services:
  account-api:
    build:
      #context: ../AccountApi
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./AccountApi:/app/AccountApi
    networks:
      - account-api-network

  testdocker-api:
    build:
      #context: ../AccountApi
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./TestDockerApi:/app/TestDockerApi
    networks:
      - account-api-network    


  sql-server-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: account-sql-server
    ports:
       - "1438:1433" 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sahil@2014
      - MSSQL_PID=Developer
    networks:
      - account-api-network

networks:
  account-api-network:
    driver: bridge
