version: '3.8'

services:
  account-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./AccountApi:/app/AccountApi
    networks:
      - account-api-network

  sql-server-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: account-sql-server
    ports:
       - "1438:1433" 
    # ports:
    #    - "1433:1433"
    #    - "1434:1434"
    # ports:
    #   - "1455:1433/tcp"
    #   - "1456:1434/tcp"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sahil@2014
      - MSSQL_PID=Developer
    networks:
      - account-api-network

networks:
  account-api-network:
    driver: bridge
